# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.

development:
  secret_key_base: 76ba17149762e0050a6295012600a9cda25b639d814f32d9f5409703832127c2f73d979de578e286c2f14de23b458e53391c77fa71f1d483eedbf90487be2b76
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 6a1b80cb406a89cd0bc705437bad5ad4aba8eeb0a5cb1edc96d1582b0bb38edeff1121f4cf3f08d90fb2b92f98ad10aac674bc60d7206bf26ba88644abdecd87

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
